name: llm_rag
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - sqlite
  - openssl
  - faiss-cpu
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==25.3.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - cryptography==44.0.2
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - dirtyjson==1.0.8
      - emoji==2.14.1
      - eval-type-backport==0.2.2
      - faiss-cpu==1.10.0
      - filelock==3.17.0
      - filetype==1.2.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.14.0
      - html5lib==1.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.31.2
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain==0.3.20
      - langchain-community==0.3.19
      - langchain-core==0.3.60
      - langchain-huggingface==0.2.0
      - langchain-ollama==0.3.3
      - langchain-text-splitters==0.3.6
      - langchainhub==0.1.21
      - langdetect==1.0.9
      - langsmith==0.3.13
      - llama-cloud==0.1.15
      - llama-cloud-services==0.6.6
      - llama-index-core==0.12.25
      - llama-parse==0.6.4.post1
      - lxml==5.3.1
      - markdown==3.7
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.30.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - olefile==0.47
      - ollama==0.4.8
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pydeck==0.9.1
      - pymupdf==1.25.4
      - pypdf==5.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-iso639==2025.2.18
      - python-magic==0.4.27
      - python-oxmsg==0.0.2
      - pytz==2025.1
      - pyyaml==6.0.2
      - rapidfuzz==3.12.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==3.4.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.39
      - streamlit==1.43.2
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - torch==2.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - types-requests==2.32.0.20250306
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - unstructured==0.17.0
      - unstructured-client==0.31.1
      - urllib3==2.3.0
      - watchdog==6.0.0
      - webencodings==0.5.1
      - wrapt==1.17.2
      - yarl==1.18.3
      - zstandard==0.23.0
